version: '3.9'

services:
  main-db:
    container_name: main-db
    image: postgres:latest
    ports:
      - "5433:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: test-password
      
  integration-db:
    container_name: integration-db
    image: postgres:latest
    ports:
      - "5434:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: test-password